In [82]:
# Importing necessary libraries
import pandas as pd
import numpy as np

# Load raw dataset
df = pd.read_csv("Shark Tank India.csv")
df.head()

,Season Number,Startup Name,Episode Number,Pitch Number,Season Start,Season End,Original Air Date,Episode Title,Anchor,Industry,...,Invested Guest Name,All Guest Names,Namita Present,Vineeta Present,Anupam Present,Aman Present,Peyush Present,Ritesh Present,Amit Present,Guest Present
0,1,BluePineFoods,1,1,20-Dec-21,4-Feb-22,20-Dec-21,Badlegi Business Ki Tasveer,Rannvijay Singh,Food and Beverage,...,Ashneer Grover,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
1,1,BoozScooters,1,2,20-Dec-21,4-Feb-22,20-Dec-21,Badlegi Business Ki Tasveer,Rannvijay Singh,Vehicles/Electrical Vehicles,...,Ashneer Grover,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
2,1,HeartUpMySleeves,1,3,20-Dec-21,4-Feb-22,20-Dec-21,Badlegi Business Ki Tasveer,Rannvijay Singh,Beauty/Fashion,...,NaN,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
3,1,TagzFoods,2,4,20-Dec-21,4-Feb-22,21-Dec-21,"Insaan, Ideas Aur Sapne",Rannvijay Singh,Food and Beverage,...,Ashneer Grover,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0
4,1,HeadAndHeart,2,5,20-Dec-21,4-Feb-22,21-Dec-21,"Insaan, Ideas Aur Sapne",Rannvijay Singh,Children/Education,...,NaN,Ashneer Grover,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0

In [83]:
# Check data structure
df.info()

# Quick statistical overview
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 634 entries, 0 to 633
Data columns (total 80 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Season Number              634 non-null    int64
 1   Startup Name               634 non-null    object
 2   Episode Number             634 non-null    int64
 3   Pitch Number               634 non-null    int64
 4   Season Start               634 non-null    object
 5   Season End                 478 non-null    object
 6   Original Air Date          603 non-null    object
 7   Episode Title              634 non-null    object
 8   Anchor                     634 non-null    object
 9   Industry                   634 non-null    object
 10  Business Description       634 non-null    object
 11  Company Website            618 non-null    object
 12  Started in                 456 non-null    float64
 13  Number of Presenters       634 non-null    int64
 14  Male Presenters            568 non-null    float64
 15  Female Presenters          382 non-null    float64
 16  Transgender Presenters     3 non-null      float64
 17  Couple Presenters          634 non-null    int64
 18  Pitchers Average Age       634 non-null    object
 19  Pitchers City              626 non-null    object
 20  Pitchers State             629 non-null    object
 21  Yearly Revenue             343 non-null    float64
 22  Monthly Sales              287 non-null    float64
 23  Gross Margin               162 non-null    float64
 24  Net Margin                 93 non-null     float64
 25  EBITDA                     81 non-null     float64
 26  Cash Burn                  97 non-null     object
 27  SKUs                       43 non-null     float64
 28  Has Patents                62 non-null     object
 29  Bootstrapped               114 non-null    object
 30  Part of Match off          6 non-null      object
 31  Original Ask Amount        634 non-null    float64
 32  Original Offered Equity    634 non-null    float64
 33  Valuation Requested        634 non-null    float64
 34  Received Offer             634 non-null    int64
 35  Accepted Offer             423 non-null    float64
 36  Total Deal Amount          360 non-null    float64
 37  Total Deal Equity          360 non-null    float64
 38  Total Deal Debt            75 non-null     float64
 39  Debt Interest              58 non-null     float64
 40  Deal Valuation             359 non-null    float64
 41  Number of Sharks in Deal   360 non-null    float64
 42  Deal Has Conditions        37 non-null     object
 43  Royalty Percentage         36 non-null     float64
 44  Royalty Recouped Amount    36 non-null     float64
 45  Advisory Shares Equity     11 non-null     float64
 46  Namita Investment Amount   114 non-null    float64
 47  Namita Investment Equity   114 non-null    float64
 48  Namita Debt Amount         21 non-null     float64
 49  Vineeta Investment Amount  89 non-null     float64
 50  Vineeta Investment Equity  89 non-null     float64
 51  Vineeta Debt Amount        15 non-null     float64
 52  Anupam Investment Amount   102 non-null    float64
 53  Anupam Investment Equity   102 non-null    float64
 54  Anupam Debt Amount         9 non-null      float64
 55  Aman Investment Amount     141 non-null    float64
 56  Aman Investment Equity     141 non-null    float64
 57  Aman Debt Amount           19 non-null     float64
 58  Peyush Investment Amount   104 non-null    float64
 59  Peyush Investment Equity   104 non-null    float64
 60  Peyush Debt Amount         13 non-null     float64
 61  Ritesh Investment Amount   52 non-null     float64
 62  Ritesh Investment Equity   52 non-null     float64
 63  Ritesh Debt Amount         14 non-null     float64
 64  Amit Investment Amount     35 non-null     float64
 65  Amit Investment Equity     35 non-null     float64
 66  Amit Debt Amount           7 non-null      float64
 67  Guest Investment Amount    63 non-null     float64
 68  Guest Investment Equity    63 non-null     float64
 69  Guest Debt Amount          6 non-null      float64
 70  Invested Guest Name        63 non-null     object
 71  All Guest Names            311 non-null    object
 72  Namita Present             495 non-null    float64
 73  Vineeta Present            428 non-null    float64
 74  Anupam Present             548 non-null    float64
 75  Aman Present               556 non-null    float64
 76  Peyush Present             388 non-null    float64
 77  Ritesh Present             138 non-null    float64
 78  Amit Present               137 non-null    float64
 79  Guest Present              311 non-null    float64
dtypes: float64(55), int64(6), object(19)
memory usage: 396.4+ KB

,Season Number,Startup Name,Episode Number,Pitch Number,Season Start,Season End,Original Air Date,Episode Title,Anchor,Industry,...,Invested Guest Name,All Guest Names,Namita Present,Vineeta Present,Anupam Present,Aman Present,Peyush Present,Ritesh Present,Amit Present,Guest Present
count,634.000000,634,634.000000,634.000000,634,478,603,634,634,634,...,63,311,495.0,428.0,548.0,556.0,388.0,138.0,137.0,311.000000
unique,NaN,634,NaN,NaN,4,3,189,190,6,18,...,15,16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,XLCinema,NaN,NaN,2-Jan-23,10-Mar-23,4-Feb-22,Unseen,Rahul Dua,Food and Beverage,...,Ashneer Grover,Ashneer Grover,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,1,NaN,NaN,169,169,7,31,319,142,...,20,92,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,2.500000,NaN,24.055205,317.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.131833
std,1.106137,NaN,15.102549,183.164316,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.338854
min,1.000000,NaN,0.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000
25%,2.000000,NaN,11.000000,159.250000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000
50%,2.000000,NaN,24.000000,317.500000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000
75%,3.000000,NaN,36.000000,475.750000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.000000
max,4.000000,NaN,52.000000,634.000000,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.000000

In [84]:
# Total null values per column
df.isnull().sum()

Season Number       0
Startup Name        0
Episode Number      0
Pitch Number        0
Season Start        0
                 ...
Aman Present       78
Peyush Present    246
Ritesh Present    496
Amit Present      497
Guest Present     323
Length: 80, dtype: int64

In [85]:
# Count and display duplicate rows
df.duplicated().sum()
df[df.duplicated()]

Empty DataFrame
Columns: [Season Number, Startup Name, Episode Number, Pitch Number, Season Start, Season End, Original Air Date, Episode Title, Anchor, Industry, Business Description, Company Website, Started in, Number of Presenters, Male Presenters, Female Presenters, Transgender Presenters, Couple Presenters, Pitchers Average Age, Pitchers City, Pitchers State, Yearly Revenue, Monthly Sales, Gross Margin, Net Margin, EBITDA, Cash Burn, SKUs, Has Patents, Bootstrapped, Part of Match off, Original Ask Amount, Original Offered Equity, Valuation Requested, Received Offer, Accepted Offer, Total Deal Amount, Total Deal Equity, Total Deal Debt, Debt Interest, Deal Valuation, Number of Sharks in Deal, Deal Has Conditions, Royalty Percentage, Royalty Recouped Amount, Advisory Shares Equity, Namita Investment Amount, Namita Investment Equity, Namita Debt Amount, Vineeta Investment Amount, Vineeta Investment Equity, Vineeta Debt Amount, Anupam Investment Amount, Anupam Investment Equity, Anupam Debt Amount, Aman Investment Amount, Aman Investment Equity, Aman Debt Amount, Peyush Investment Amount, Peyush Investment Equity, Peyush Debt Amount, Ritesh Investment Amount, Ritesh Investment Equity, Ritesh Debt Amount, Amit Investment Amount, Amit Investment Equity, Amit Debt Amount, Guest Investment Amount, Guest Investment Equity, Guest Debt Amount, Invested Guest Name, All Guest Names, Namita Present, Vineeta Present, Anupam Present, Aman Present, Peyush Present, Ritesh Present, Amit Present, Guest Present]
Index: []

[0 rows x 80 columns]

In [86]:
# Check unique values per column to understand data types and quality
for col in df.columns:
    print(f"\nColumn: {col}")
    print(df[col].value_counts(dropna=False).head(5))

Column: Season Number
Season Number
2    169
3    157
4    156
1    152
Name: count, dtype: int64

Column: Startup Name
Startup Name
XLCinema            1
BluePineFoods       1
BoozScooters        1
HeartUpMySleeves    1
TagzFoods           1
Name: count, dtype: int64

Column: Episode Number
Episode Number
0     31
27    14
32    14
23    14
18    14
Name: count, dtype: int64

Column: Pitch Number
Pitch Number
634    1
1      1
2      1
3      1
4      1
Name: count, dtype: int64

Column: Season Start
Season Start
2-Jan-23     169
22-Jan-24    157
6-Jan-25     156
20-Dec-21    152
Name: count, dtype: int64

Column: Season End
Season End
10-Mar-23    169
31-Mar-24    157
NaN          156
4-Feb-22     152
Name: count, dtype: int64

Column: Original Air Date
Original Air Date
NaN          31
4-Feb-22      7
10-Mar-23     6
13-Jan-22     4
28-Dec-21     4
Name: count, dtype: int64

Column: Episode Title
Episode Title
Unseen                                31
Gateway To Shark Tank India            8
Pitch Perfect                          7
Forming An Idea And Bagging A Deal     4
A Never Give Up Spirit                 4
Name: count, dtype: int64

Column: Anchor
Anchor
Rahul Dua                      319
Rannvijay Singh                152
Sahiba Bali/Aashish Solanki     92
Aashish Solanki                 52
Sahiba Bali                     12
Name: count, dtype: int64

Column: Industry
Industry
Food and Beverage      142
Beauty/Fashion         127
Technology/Software     58
Medical/Health          56
Manufacturing           52
Name: count, dtype: int64

Column: Business Description
Business Description
Travel Bags             2
Healthy Snacks          2
Energy Drink            2
Online plant nursery    2
Kids Audio Platform     1
Name: count, dtype: int64

Column: Company Website
Company Website
NaN                               16
https://www.mepackfitness.com/     1
https://baccabucci.com/            1
https://www.vobble.fun/            1
https://erotissch.com/             1
Name: count, dtype: int64

Column: Started in
Started in
NaN       178
2019.0     75
2021.0     70
2020.0     69
2018.0     48
Name: count, dtype: int64

Column: Number of Presenters
Number of Presenters
2    334
1    165
3    110
4     21
5      3
Name: count, dtype: int64

Column: Male Presenters
Male Presenters
1.0    281
2.0    187
NaN     66
3.0     65
0.0     22
Name: count, dtype: int64

Column: Female Presenters
Female Presenters
NaN    252
1.0    244
0.0     82
2.0     52
3.0      4
Name: count, dtype: int64

Column: Transgender Presenters
Transgender Presenters
NaN    631
1.0      3
Name: count, dtype: int64

Column: Couple Presenters
Couple Presenters
0    522
1    112
Name: count, dtype: int64

Column: Pitchers Average Age
Pitchers Average Age
Middle    475
Young     153
Old         6
Name: count, dtype: int64

Column: Pitchers City
Pitchers City
Mumbai       94
Delhi        89
Bangalore    64
Pune         35
Ahmedabad    28
Name: count, dtype: int64

Column: Pitchers State
Pitchers State
Maharashtra    157
Delhi           88
Karnataka       69
Gujarat         54
Haryana         42
Name: count, dtype: int64

Column: Yearly Revenue
Yearly Revenue
NaN       291
0.0        25
100.0       9
120.0       9
1000.0      8
Name: count, dtype: int64

Column: Monthly Sales
Monthly Sales
NaN      347
2.0        9
100.0      8
1.0        7
10.0       7
Name: count, dtype: int64

Column: Gross Margin
Gross Margin
NaN     472
70.0     15
50.0     14
60.0     14
80.0     10
Name: count, dtype: int64

Column: Net Margin
Net Margin
NaN     541
20.0      9
15.0      9
30.0      8
25.0      7
Name: count, dtype: int64

Column: EBITDA
EBITDA
NaN     553
15.0      7
20.0      6
10.0      5
18.0      5
Name: count, dtype: int64

Column: Cash Burn
Cash Burn
NaN    537
yes     97
Name: count, dtype: int64

Column: SKUs
SKUs
NaN      591
12.0       3
20.0       3
250.0      3
8.0        2
Name: count, dtype: int64

Column: Has Patents
Has Patents
NaN    572
yes     62
Name: count, dtype: int64

Column: Bootstrapped
Bootstrapped
NaN       520
funded     78
yes        36
Name: count, dtype: int64

Column: Part of Match off
Part of Match off
NaN    628
yes      6
Name: count, dtype: int64

Column: Original Ask Amount
Original Ask Amount
50.0     141
100.0    122
75.0      67
60.0      42
80.0      36
Name: count, dtype: int64

Column: Original Offered Equity
Original Offered Equity
1.0     138
2.0      92
5.0      90
3.0      50
10.0     46
Name: count, dtype: int64

Column: Valuation Requested
Valuation Requested
5000.0     53
1000.0     49
10000.0    44
4000.0     43
2500.0     39
Name: count, dtype: int64

Column: Received Offer
Received Offer
1    423
0    211
Name: count, dtype: int64

Column: Accepted Offer
Accepted Offer
1.0    360
NaN    211
0.0     63
Name: count, dtype: int64

Column: Total Deal Amount
Total Deal Amount
NaN      274
50.0      76
100.0     66
75.0      31
60.0      23
Name: count, dtype: int64

Column: Total Deal Equity
Total Deal Equity
NaN     274
10.0     42
1.0      35
5.0      34
4.0      31
Name: count, dtype: int64

Column: Total Deal Debt
Total Deal Debt
NaN     559
50.0     20
25.0     12
40.0      8
30.0      6
Name: count, dtype: int64

Column: Debt Interest
Debt Interest
NaN     576
10.0     28
12.0     13
9.0       5
8.0       4
Name: count, dtype: int64

Column: Deal Valuation
Deal Valuation
NaN       275
1000.0     37
2000.0     23
500.0      22
2500.0     17
Name: count, dtype: int64

Column: Number of Sharks in Deal
Number of Sharks in Deal
NaN    274
1.0    160
2.0    113
3.0     48
4.0     21
Name: count, dtype: int64

Column: Deal Has Conditions
Deal Has Conditions
NaN    597
yes     37
Name: count, dtype: int64

Column: Royalty Percentage
Royalty Percentage
NaN    598
1.0     15
2.0      8
0.5      6
3.0      4
Name: count, dtype: int64

Column: Royalty Recouped Amount
Royalty Recouped Amount
NaN      598
100.0      7
150.0      6
75.0       3
70.0       3
Name: count, dtype: int64

Column: Advisory Shares Equity
Advisory Shares Equity
NaN    623
2.5      2
1.5      2
0.6      2
1.0      2
Name: count, dtype: int64

Column: Namita Investment Amount
Namita Investment Amount
NaN     520
50.0     17
25.0     16
20.0     12
40.0      7
Name: count, dtype: int64

Column: Namita Investment Equity
Namita Investment Equity
NaN    520
1.0     18
5.0     12
2.0     11
0.5      9
Name: count, dtype: int64

Column: Namita Debt Amount
Namita Debt Amount
NaN     613
50.0      5
25.0      3
12.5      2
40.0      2
Name: count, dtype: int64

Column: Vineeta Investment Amount
Vineeta Investment Amount
NaN     545
50.0     16
20.0     11
25.0     11
40.0      5
Name: count, dtype: int64

Column: Vineeta Investment Equity
Vineeta Investment Equity
NaN    545
5.0     10
1.0     10
2.5      9
2.0      7
Name: count, dtype: int64

Column: Vineeta Debt Amount
Vineeta Debt Amount
NaN     619
50.0      4
12.5      3
30.0      2
20.0      2
Name: count, dtype: int64

Column: Anupam Investment Amount
Anupam Investment Amount
NaN     532
50.0     19
20.0     15
25.0     12
10.0      5
Name: count, dtype: int64

Column: Anupam Investment Equity
Anupam Investment Equity
NaN     532
1.0      11
5.0      10
2.0       8
10.0      7
Name: count, dtype: int64

Column: Anupam Debt Amount
Anupam Debt Amount
NaN     625
50.0      2
25.0      2
15.0      1
12.5      1
Name: count, dtype: int64

Column: Aman Investment Amount
Aman Investment Amount
NaN     493
50.0     24
25.0     14
20.0     11
15.0      8
Name: count, dtype: int64

Column: Aman Investment Equity
Aman Investment Equity
NaN    493
2.0     15
1.0     13
5.0      9
2.5      9
Name: count, dtype: int64

Column: Aman Debt Amount
Aman Debt Amount
NaN     615
50.0      2
25.0      2
80.0      2
40.0      2
Name: count, dtype: int64

Column: Peyush Investment Amount
Peyush Investment Amount
NaN     530
50.0     19
25.0     17
20.0      8
10.0      8
Name: count, dtype: int64

Column: Peyush Investment Equity
Peyush Investment Equity
NaN     530
1.0      15
2.0      11
5.0      10
10.0      8
Name: count, dtype: int64

Column: Peyush Debt Amount
Peyush Debt Amount
NaN     621
25.0      5
10.0      2
50.0      2
20.0      1
Name: count, dtype: int64

Column: Ritesh Investment Amount
Ritesh Investment Amount
NaN     582
50.0      9
25.0      6
40.0      4
30.0      4
Name: count, dtype: int64

Column: Ritesh Investment Equity
Ritesh Investment Equity
NaN    582
2.0      9
0.5      7
2.5      6
5.0      4
Name: count, dtype: int64

Column: Ritesh Debt Amount
Ritesh Debt Amount
NaN     620
25.0      5
50.0      2
15.0      1
75.0      1
Name: count, dtype: int64

Column: Amit Investment Amount
Amit Investment Amount
NaN     599
25.0      5
10.0      4
40.0      3
20.0      3
Name: count, dtype: int64

Column: Amit Investment Equity
Amit Investment Equity
NaN     599
5.0       6
1.0       4
2.0       3
10.0      3
Name: count, dtype: int64

Column: Amit Debt Amount
Amit Debt Amount
NaN     627
40.0      2
10.0      1
25.0      1
45.0      1
Name: count, dtype: int64

Column: Guest Investment Amount
Guest Investment Amount
NaN     571
25.0     12
20.0      8
50.0      8
10.0      4
Name: count, dtype: int64

Column: Guest Investment Equity
Guest Investment Equity
NaN    571
5.0      6
2.5      6
1.0      5
2.0      5
Name: count, dtype: int64

Column: Guest Debt Amount
Guest Debt Amount
NaN     628
15.0      1
99.0      1
34.5      1
12.5      1
Name: count, dtype: int64

Column: Invested Guest Name
Invested Guest Name
NaN               571
Ashneer Grover     20
Kunal Bahl         10
Ghazal Alagh        7
Azhar Iqubal        6
Name: count, dtype: int64

Column: All Guest Names
All Guest Names
NaN               323
Ashneer Grover     92
Kunal Bahl         82
Azhar Iqubal       25
Ghazal Alagh       20
Name: count, dtype: int64

Column: Namita Present
Namita Present
1.0    495
NaN    139
Name: count, dtype: int64

Column: Vineeta Present
Vineeta Present
1.0    428
NaN    206
Name: count, dtype: int64

Column: Anupam Present
Anupam Present
1.0    548
NaN     86
Name: count, dtype: int64

Column: Aman Present
Aman Present
1.0    556
NaN     78
Name: count, dtype: int64

Column: Peyush Present
Peyush Present
1.0    388
NaN    246
Name: count, dtype: int64

Column: Ritesh Present
Ritesh Present
NaN    496
1.0    138
Name: count, dtype: int64

Column: Amit Present
Amit Present
NaN    497
1.0    137
Name: count, dtype: int64

Column: Guest Present
Guest Present
NaN    323
1.0    270
2.0     41
Name: count, dtype: int64

In [87]:
# Make a copy for cleaning
df_cleaned = df.copy()

In [88]:
# Remove leading/trailing whitespaces and convert to snake_case
df_cleaned.columns = df_cleaned.columns.str.strip().str.lower().str.replace(" ", "_")

In [89]:
# Convert Episode number to integer if needed
df_cleaned['episode_number'] = df_cleaned['episode_number'].astype('Int64')

In [91]:
# Check final cleaned structure
df_cleaned.info()

# Save to CSV
df_cleaned.to_csv("Cleaned_Shark_Tank_India.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 634 entries, 0 to 633
Data columns (total 80 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   season_number              634 non-null    int64
 1   startup_name               634 non-null    object
 2   episode_number             634 non-null    Int64
 3   pitch_number               634 non-null    int64
 4   season_start               634 non-null    datetime64[ns]
 5   season_end                 478 non-null    datetime64[ns]
 6   original_air_date          603 non-null    datetime64[ns]
 7   episode_title              634 non-null    object
 8   anchor                     634 non-null    object
 9   industry                   634 non-null    object
 10  business_description       634 non-null    object
 11  company_website            618 non-null    object
 12  started_in                 456 non-null    float64
 13  number_of_presenters       634 non-null    int64
 14  male_presenters            568 non-null    float64
 15  female_presenters          382 non-null    float64
 16  transgender_presenters     3 non-null      float64
 17  couple_presenters          634 non-null    int64
 18  pitchers_average_age       634 non-null    object
 19  pitchers_city              626 non-null    object
 20  pitchers_state             629 non-null    object
 21  yearly_revenue             343 non-null    float64
 22  monthly_sales              287 non-null    float64
 23  gross_margin               162 non-null    float64
 24  net_margin                 93 non-null     float64
 25  ebitda                     81 non-null     float64
 26  cash_burn                  97 non-null     object
 27  skus                       43 non-null     float64
 28  has_patents                62 non-null     object
 29  bootstrapped               114 non-null    object
 30  part_of_match_off          6 non-null      object
 31  original_ask_amount        634 non-null    float64
 32  original_offered_equity    634 non-null    float64
 33  valuation_requested        634 non-null    float64
 34  received_offer             634 non-null    int64
 35  accepted_offer             423 non-null    float64
 36  total_deal_amount          360 non-null    float64
 37  total_deal_equity          360 non-null    float64
 38  total_deal_debt            75 non-null     float64
 39  debt_interest              58 non-null     float64
 40  deal_valuation             359 non-null    float64
 41  number_of_sharks_in_deal   360 non-null    float64
 42  deal_has_conditions        37 non-null     object
 43  royalty_percentage         36 non-null     float64
 44  royalty_recouped_amount    36 non-null     float64
 45  advisory_shares_equity     11 non-null     float64
 46  namita_investment_amount   114 non-null    float64
 47  namita_investment_equity   114 non-null    float64
 48  namita_debt_amount         21 non-null     float64
 49  vineeta_investment_amount  89 non-null     float64
 50  vineeta_investment_equity  89 non-null     float64
 51  vineeta_debt_amount        15 non-null     float64
 52  anupam_investment_amount   102 non-null    float64
 53  anupam_investment_equity   102 non-null    float64
 54  anupam_debt_amount         9 non-null      float64
 55  aman_investment_amount     141 non-null    float64
 56  aman_investment_equity     141 non-null    float64
 57  aman_debt_amount           19 non-null     float64
 58  peyush_investment_amount   104 non-null    float64
 59  peyush_investment_equity   104 non-null    float64
 60  peyush_debt_amount         13 non-null     float64
 61  ritesh_investment_amount   52 non-null     float64
 62  ritesh_investment_equity   52 non-null     float64
 63  ritesh_debt_amount         14 non-null     float64
 64  amit_investment_amount     35 non-null     float64
 65  amit_investment_equity     35 non-null     float64
 66  amit_debt_amount           7 non-null      float64
 67  guest_investment_amount    63 non-null     float64
 68  guest_investment_equity    63 non-null     float64
 69  guest_debt_amount          6 non-null      float64
 70  invested_guest_name        63 non-null     object
 71  all_guest_names            311 non-null    object
 72  namita_present             495 non-null    float64
 73  vineeta_present            428 non-null    float64
 74  anupam_present             548 non-null    float64
 75  aman_present               556 non-null    float64
 76  peyush_present             388 non-null    float64
 77  ritesh_present             138 non-null    float64
 78  amit_present               137 non-null    float64
 79  guest_present              311 non-null    float64
dtypes: Int64(1), datetime64[ns](3), float64(55), int64(5), object(16)
memory usage: 397.0+ KB